# Site settings
title: Adam's Blog
email: worthina@purdue.edu
description: > # this means to ignore newlines until "baseurl:"
  A technical blog I started to share my ideas and experiences
  with the world. Stay tuned!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  AdamWorthington

# Build settings
markdown: kramdown
